import { useEffect } from 'react';
import { Stack, useRouter, useSegments } from 'expo-router';
import { StatusBar } from 'expo-status-bar';
import * as SplashScreen from 'expo-splash-screen';
import { useFonts } from 'expo-font';
import {
  Inter_400Regular,
  Inter_500Medium,
  Inter_600SemiBold,
  Inter_700Bold,
  Inter_800ExtraBold,
} from '@expo-google-fonts/inter';
import { useAuthStore } from '../stores/useAuthStore';

SplashScreen.preventAutoHideAsync();

export default function RootLayout() {
  const [fontsLoaded] = useFonts({
    Inter_400Regular,
    Inter_500Medium,
    Inter_600SemiBold,
    Inter_700Bold,
    Inter_800ExtraBold,
  });

  const booting = useAuthStore((st) => st.booting);
  const user = useAuthStore((st) => st.user);
  const boot = useAuthStore((st) => st.boot);
  const segments = useSegments();
  const router = useRouter();

  // Exchange the stored refresh token for a session before deciding anything.
  useEffect(() => {
    void boot();
  }, [boot]);

  // Hold the native splash until both the fonts and the session are settled.
  // Hiding earlier shows the login screen for a frame to somebody who is
  // already signed in, which reads as being logged out.
  useEffect(() => {
    if (fontsLoaded && !booting) void SplashScreen.hideAsync();
  }, [fontsLoaded, booting]);

  useEffect(() => {
    if (booting) return;
    // segments is typed from the generated route tree, which is regenerated by
    // Metro - so compare as strings rather than relying on its shape here.
    const path = (segments as string[]).join('/');
    const inAuth = path.startsWith('(auth)');
    const needsName = user && !user.name;

    if (!user && !inAuth) {
      router.replace('/(auth)/login');
    } else if (user && needsName && !path.includes('signup')) {
      // A driver has to ask for someone at pickup, so the name is the one
      // thing collected before a trip can be booked.
      router.replace('/(auth)/signup');
    } else if (user && !needsName && inAuth) {
      router.replace('/(tabs)');
    }
  }, [booting, user, segments, router]);

  if (!fontsLoaded || booting) return null;

  return (
    <>
      <StatusBar style="dark" />
      <Stack screenOptions={{ headerShown: false }}>
        <Stack.Screen name="(auth)" />
        <Stack.Screen name="(tabs)" />
        <Stack.Screen name="(booking)" options={{ animation: 'slide_from_right' }} />
        <Stack.Screen name="+not-found" />
      </Stack>
    </>
  );
}
